import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  Apple, Bell, CalendarDays, ChevronRight, Cloud, Dumbbell, Euro, FileText,
  HeartPulse, Home, ListChecks, NotebookText, Pill, Plus, ReceiptText,
  Salad, Settings, ShoppingCart, Sparkles, Sun, Thermometer, Timer, Wallet,
  Wind, CloudRain, CloudSnow, Zap
} from 'lucide-react';
import './styles.css';

const STORAGE_KEY = 'armand_ecosystem_app_state';
const todayISO = () => new Date().toISOString().slice(0, 10);
const monthISO = () => new Date().toISOString().slice(0, 7);

const FINANCE_CATEGORIES = ['Affitto / mutuo','Bollette','Spesa alimentare','Trasporti','Abbonamenti','Svago','Salute','Fitness','Extra','Risparmio','Emergenze'];
const SHOPPING_CATEGORIES = ['Frutta','Verdura','Carne','Pesce','Latticini','Pasta / riso / cereali','Dispensa','Surgelati','Bevande','Casa','Altro'];
const SECTIONS = [
  ['dashboard','Dashboard',Home], ['meals','Pasti di oggi',Salad], ['recipes','Ricette',ReceiptText], ['shopping','Lista spesa',ShoppingCart],
  ['finance','Finanza',Wallet], ['workouts','Allenamenti',Dumbbell], ['exercises','Esercizi',ListChecks], ['fitness','Fitness',HeartPulse],
  ['health','Salute',HeartPulse], ['pressure','Pressione',HeartPulse], ['temperature','Temperatura',Thermometer], ['medications','Farmaci',Pill],
  ['supplements','Integratori',Apple], ['notes','Note',NotebookText], ['weather','Meteo',Cloud], ['notifications','Promemoria',Bell],
  ['suggestions','Suggerimenti',Sparkles], ['settings','Impostazioni',Settings]
];

const starterState = {
  user: { name: 'Armand' },
  currentDate: todayISO(),
  currentScreen: 'dashboard',
  dailyMeals: { date: todayISO(), breakfast: null, lunch: null, dinner: null, snack: null },
  recipes: [
    { id:'recipe_demo_1', name:'Pasta integrale con tonno', mealType:'pranzo', prepTime:18, ingredients:[
      {name:'Pasta integrale', quantity:100, unit:'g', category:'Pasta / riso / cereali', estimatedPrice:0.7},
      {name:'Tonno', quantity:1, unit:'lattina', category:'Pesce', estimatedPrice:1.8},
      {name:'Pomodori', quantity:2, unit:'pz', category:'Verdura', estimatedPrice:1.2}
    ], steps:['Cuoci la pasta', 'Aggiungi tonno e pomodori', 'Condisci e servi']},
    { id:'recipe_demo_2', name:'Yogurt con frutta', mealType:'colazione', prepTime:5, ingredients:[
      {name:'Yogurt greco', quantity:1, unit:'vasetto', category:'Latticini', estimatedPrice:1.1},
      {name:'Banana', quantity:1, unit:'pz', category:'Frutta', estimatedPrice:0.4}
    ], steps:['Taglia la frutta', 'Aggiungi yogurt', 'Mescola']}
  ],
  shoppingList: [],
  finance: { selectedMonth: monthISO(), months: {} },
  workouts: [{ id:'workout_demo_1', name:'Total body leggero', date:todayISO(), time:'18:00', duration:45, muscleGroup:'Generale', notes:'Sessione controllata', status:'programmato', reminderEnabled:true, exercises:[
    {id:'exercise_demo_1', name:'Squat', sets:3, reps:12, weight:0, restSeconds:60, notes:'Corpo libero', completed:false},
    {id:'exercise_demo_2', name:'Panca piana', sets:4, reps:10, weight:70, restSeconds:90, notes:'Buona esecuzione', completed:false}
  ]}],
  health: { bloodPressure: [], bodyTemperature: [], medications: [], supplements: [] },
  notes: [{id:'note_demo_1', title:'Obiettivo settimana', text:'Controllare spesa, pressione e allenamento.', category:'Generale', date:todayISO(), time:'09:00', pinned:true}],
  weather: { city:'Posizione attuale', temperature:22, condition:'Sole', icon:'sun', min:17, max:25, rainProbability:10, wind:'8 km/h', lastUpdated:new Date().toISOString() },
  notifications: [], widgets: [], suggestions: [], shoppingSummary:null, financeSummary:null, fitnessSummary:null, healthSummary:null, budgetAlerts: [],
  appleHealth: { connected:false, lastSync:null, permissions:{} }
};

let appState = structuredClone(starterState);

function createId(prefix) { return `${prefix}_${Date.now()}_${Math.floor(Math.random() * 10000)}`; }
function createShoppingKey(name, unit, category) { return `${String(name).toLowerCase().trim()}_${String(unit).toLowerCase().trim()}_${String(category).toLowerCase().trim()}`; }
function saveState() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(appState)); return {success:true}; } catch { return {success:false, errors:['Impossibile salvare i dati']}; } }
function loadState() { try { const saved = localStorage.getItem(STORAGE_KEY); if(saved) Object.assign(appState, JSON.parse(saved)); bootstrap(); return {success:true}; } catch { bootstrap(); return {success:false, errors:['Impossibile caricare i dati salvati']}; } }
function ensureCurrentFinanceMonth() { const m = appState.finance.selectedMonth; if(!appState.finance.months[m]) appState.finance.months[m] = { startingBalance:0, incomes:[], expenses:[], budgets:[], savingGoal:0, totalIncome:0, totalExpenses:0, availableBalance:0, expectedSavings:0, savingGoalDelta:0 }; return appState.finance.months[m]; }
function validateRecipe(recipe){ const errors=[]; if(!recipe.name) errors.push('Inserisci il nome della ricetta'); if(!recipe.ingredients?.length) errors.push('Aggiungi almeno un ingrediente'); recipe.ingredients?.forEach(i=>{ if(!i.name) errors.push('Un ingrediente non ha il nome'); if(!i.quantity || i.quantity<=0) errors.push('Quantità non valida per '+(i.name||'ingrediente')); if(!i.unit) errors.push('Manca unità per '+(i.name||'ingrediente')); }); return errors; }
function addRecipe(recipe){ const errors=validateRecipe(recipe); if(errors.length) return {success:false, errors}; const newRecipe={id:createId('recipe'), name:recipe.name, mealType:recipe.mealType||'altro', prepTime:Number(recipe.prepTime||0), ingredients:recipe.ingredients||[], steps:recipe.steps||[]}; appState.recipes.push(newRecipe); syncEcosystem('RECIPE_ADDED', newRecipe); return {success:true, recipe:newRecipe}; }
function editRecipe(recipeId, updatedData){ const r=appState.recipes.find(x=>x.id===recipeId); if(!r) return {success:false, errors:['Ricetta non trovata']}; const next={...r,...updatedData}; const errors=validateRecipe(next); if(errors.length) return {success:false, errors}; Object.assign(r,next); syncEcosystem('RECIPE_UPDATED',{recipeId}); return {success:true, recipe:r}; }
function deleteRecipe(recipeId){ const idx=appState.recipes.findIndex(r=>r.id===recipeId); if(idx<0) return {success:false, errors:['Ricetta non trovata']}; appState.recipes.splice(idx,1); ['breakfast','lunch','dinner','snack'].forEach(k=>{ if(appState.dailyMeals[k]?.recipeId===recipeId) appState.dailyMeals[k]=null; }); appState.shoppingList=appState.shoppingList.filter(i=>!i.recipeIds?.includes(recipeId)); syncEcosystem('RECIPE_DELETED',{recipeId}); return {success:true}; }
function assignRecipeToMeal(mealType, recipeId){ const recipe=appState.recipes.find(r=>r.id===recipeId); if(!recipe) return {success:false, errors:['Ricetta non trovata']}; const map={colazione:'breakfast',pranzo:'lunch',cena:'dinner',snack:'snack',breakfast:'breakfast',lunch:'lunch',dinner:'dinner'}; const key=map[mealType]; if(!key) return {success:false, errors:['Tipo pasto non valido']}; appState.dailyMeals[key]={name:recipe.name, recipeId:recipe.id}; syncEcosystem('RECIPE_ASSIGNED_TO_MEAL',{mealType,recipeId}); return {success:true}; }
function generateShoppingListFromDailyMeals(){ const recipeIds=['breakfast','lunch','dinner','snack'].map(k=>appState.dailyMeals[k]?.recipeId).filter(Boolean); const manual=appState.shoppingList.filter(i=>i.source==='Inserimento manuale'); const preserved={}; appState.shoppingList.filter(i=>i.source!=='Inserimento manuale').forEach(i=>preserved[createShoppingKey(i.name,i.unit,i.category)]={purchased:i.purchased, estimatedPrice:i.estimatedPrice, realPrice:i.realPrice}); const map={}; recipeIds.forEach(id=>{ const recipe=appState.recipes.find(r=>r.id===id); if(!recipe) return; recipe.ingredients.forEach(ing=>{ const category=ing.category||'Altro', unit=ing.unit||'', key=createShoppingKey(ing.name,unit,category); if(!map[key]){ const p=preserved[key]||{}; map[key]={id:createId('item'), name:ing.name, quantity:Number(ing.quantity||0), unit, category, purchased:p.purchased||false, source:recipe.name, sources:[recipe.name], recipeId:recipe.id, recipeIds:[recipe.id], estimatedPrice:p.estimatedPrice ?? ing.estimatedPrice ?? null, realPrice:p.realPrice ?? null}; } else { map[key].quantity+=Number(ing.quantity||0); if(!map[key].sources.includes(recipe.name)) map[key].sources.push(recipe.name); if(!map[key].recipeIds.includes(recipe.id)) map[key].recipeIds.push(recipe.id); map[key].source=map[key].sources.join(', '); } }); }); appState.shoppingList=[...manual,...Object.values(map)]; recalculateShoppingTotals(); return appState.shoppingList; }
function addManualShoppingItem(name, quantity, unit='', category='Altro', estimatedPrice=null){ if(!name||!quantity) return {success:false, errors:['Inserisci nome prodotto e quantità']}; const ex=appState.shoppingList.find(i=>i.name.toLowerCase()===name.toLowerCase()&&i.source==='Inserimento manuale'&&i.unit===unit&&i.category===category); if(ex) ex.quantity+=Number(quantity); else appState.shoppingList.push({id:createId('item'), name, quantity:Number(quantity), unit, category, purchased:false, source:'Inserimento manuale', sources:['Inserimento manuale'], recipeId:null, recipeIds:[], estimatedPrice:estimatedPrice===''?null:Number(estimatedPrice??0), realPrice:null}); syncEcosystem('SHOPPING_ITEM_ADDED',{}); return {success:true}; }
function deleteShoppingItem(itemId){ appState.shoppingList=appState.shoppingList.filter(i=>i.id!==itemId); syncEcosystem('SHOPPING_ITEM_DELETED',{itemId}); return {success:true}; }
function togglePurchasedItem(itemId){ const i=appState.shoppingList.find(x=>x.id===itemId); if(!i) return {success:false, errors:['Prodotto non trovato']}; i.purchased=!i.purchased; syncEcosystem('SHOPPING_ITEM_PURCHASED',{itemId}); return {success:true}; }
function updateShoppingItemQuantity(itemId,newQuantity,newUnit){ const i=appState.shoppingList.find(x=>x.id===itemId); if(!i) return {success:false, errors:['Prodotto non trovato']}; i.quantity=Number(newQuantity); if(newUnit!==undefined) i.unit=newUnit; syncEcosystem('SHOPPING_ITEM_UPDATED',{}); return {success:true}; }
function updateEstimatedPrice(itemId, estimatedPrice){ const i=appState.shoppingList.find(x=>x.id===itemId); if(!i) return {success:false, errors:['Prodotto non trovato']}; i.estimatedPrice=Number(estimatedPrice||0); syncEcosystem('ESTIMATED_PRICE_ADDED',{}); return {success:true}; }
function updateRealPrice(itemId, realPrice){ const i=appState.shoppingList.find(x=>x.id===itemId); if(!i) return {success:false, errors:['Prodotto non trovato']}; i.realPrice=Number(realPrice||0); syncEcosystem('REAL_PRICE_ADDED',{}); return {success:true}; }
function mergeDuplicateShoppingItems(){ const map={}; appState.shoppingList.forEach(item=>{ const key=createShoppingKey(item.name,item.unit,item.category); if(!map[key]) map[key]={...item, sources:item.sources||[item.source], recipeIds:item.recipeIds||(item.recipeId?[item.recipeId]:[])}; else { map[key].quantity+=Number(item.quantity||0); map[key].purchased=map[key].purchased&&item.purchased; map[key].estimatedPrice=map[key].estimatedPrice??item.estimatedPrice; map[key].realPrice=map[key].realPrice??item.realPrice; [...(item.sources||[item.source])].forEach(s=>s&&!map[key].sources.includes(s)&&map[key].sources.push(s)); [...(item.recipeIds||[])].forEach(r=>r&&!map[key].recipeIds.includes(r)&&map[key].recipeIds.push(r)); map[key].source=map[key].sources.join(', '); } }); appState.shoppingList=Object.values(map); syncEcosystem('SHOPPING_ITEMS_MERGED',{}); return {success:true}; }
function recalculateShoppingTotals(){ const totalItems=appState.shoppingList.length, purchasedItems=appState.shoppingList.filter(i=>i.purchased).length, notPurchasedItems=appState.shoppingList.filter(i=>!i.purchased).length; const estimatedTotal=appState.shoppingList.reduce((s,i)=>s+Number(i.estimatedPrice||0),0); const realTotal=appState.shoppingList.reduce((s,i)=>s+(i.purchased?Number(i.realPrice||0):0),0); appState.shoppingSummary={totalItems,purchasedItems,notPurchasedItems,estimatedTotal,realTotal,difference:realTotal-estimatedTotal}; return appState.shoppingSummary; }
function updateFoodExpenseFromShopping(){ const m=ensureCurrentFinanceMonth(); const total=appState.shoppingList.reduce((s,i)=>s+(i.purchased?Number(i.realPrice||0):0),0); const e=m.expenses.find(x=>x.name==='Spesa alimentare da lista'); if(e) e.amount=total; else if(total>0) m.expenses.push({id:createId('expense'), name:'Spesa alimentare da lista', amount:total, category:'Spesa alimentare', type:'variable', date:appState.currentDate, automatic:true}); }
function addIncome(name, amount, type='variable', date=appState.currentDate, reminder=null){ if(!name||!amount) return {success:false, errors:['Inserisci entrata valida']}; const m=ensureCurrentFinanceMonth(); const income={id:createId('income'), name, amount:Number(amount), type, date, reminder}; m.incomes.push(income); if(reminder?.enabled) scheduleReminder('income',income.id,'Promemoria entrata',`${appState.user.name}, entrata prevista: ${name} da €${amount}`, reminder.date||date, reminder.time||'09:00','Finanza'); syncEcosystem('INCOME_ADDED',income); return {success:true,income}; }
function editIncome(incomeId, updatedData){ const i=ensureCurrentFinanceMonth().incomes.find(x=>x.id===incomeId); if(!i) return {success:false}; Object.assign(i,updatedData); syncEcosystem('INCOME_UPDATED',{}); return {success:true,income:i}; }
function deleteIncome(incomeId){ const m=ensureCurrentFinanceMonth(); m.incomes=m.incomes.filter(i=>i.id!==incomeId); syncEcosystem('INCOME_DELETED',{}); return {success:true}; }
function addExpense(name, amount, category='Extra', type='variable', date=appState.currentDate, reminder=null){ if(!name||!amount) return {success:false, errors:['Inserisci uscita valida']}; const m=ensureCurrentFinanceMonth(); const expense={id:createId('expense'), name, amount:Number(amount), category, type, date, reminder, automatic:false}; m.expenses.push(expense); if(reminder?.enabled) scheduleReminder('expense',expense.id,'Scadenza finanza',`${appState.user.name}, ricordati di pagare ${name} da €${amount}`, reminder.date||date, reminder.time||'09:00','Finanza'); syncEcosystem('EXPENSE_ADDED',expense); return {success:true,expense}; }
function editExpense(expenseId, updatedData){ const e=ensureCurrentFinanceMonth().expenses.find(x=>x.id===expenseId); if(!e) return {success:false}; Object.assign(e,updatedData); syncEcosystem('EXPENSE_UPDATED',{}); return {success:true,expense:e}; }
function deleteExpense(expenseId){ const m=ensureCurrentFinanceMonth(); m.expenses=m.expenses.filter(e=>e.id!==expenseId); syncEcosystem('EXPENSE_DELETED',{}); return {success:true}; }
function addOrUpdateBudget(category, limit){ const m=ensureCurrentFinanceMonth(); const b=m.budgets.find(x=>x.category===category); if(b) b.limit=Number(limit); else m.budgets.push({category, limit:Number(limit), used:0, remaining:Number(limit), percentageUsed:0}); syncEcosystem('BUDGET_CHANGED',{}); return {success:true}; }
function deleteBudget(category){ const m=ensureCurrentFinanceMonth(); m.budgets=m.budgets.filter(b=>b.category!==category); syncEcosystem('BUDGET_CHANGED',{}); return {success:true}; }
function calculateFinanceSummary(){ const m=ensureCurrentFinanceMonth(); const totalIncome=m.incomes.reduce((s,i)=>s+Number(i.amount||0),0); const totalExpenses=m.expenses.reduce((s,e)=>s+Number(e.amount||0),0); const availableBalance=Number(m.startingBalance||0)+totalIncome-totalExpenses; const expectedSavings=availableBalance; const savingGoalDelta=availableBalance-Number(m.savingGoal||0); return {totalIncome,totalExpenses,availableBalance,savingGoal:Number(m.savingGoal||0),expectedSavings,savingGoalDelta}; }
function updateFinanceSummary(){ const m=ensureCurrentFinanceMonth(); const s=calculateFinanceSummary(); Object.assign(m,{totalIncome:s.totalIncome,totalExpenses:s.totalExpenses,availableBalance:s.availableBalance,expectedSavings:s.expectedSavings,savingGoalDelta:s.savingGoalDelta}); appState.financeSummary=s; return s; }
function duplicatePreviousMonth(previousMonthKey,newMonthKey){ const prev=appState.finance.months[previousMonthKey]; if(!prev) return {success:false, errors:['Mese precedente non trovato']}; appState.finance.months[newMonthKey]=structuredClone(prev); const n=appState.finance.months[newMonthKey]; n.expenses=n.expenses.filter(e=>e.name!=='Spesa alimentare da lista').map(e=>({...e,id:createId('expense'),date:`${newMonthKey}-01`})); n.incomes=n.incomes.map(i=>({...i,id:createId('income'),date:`${newMonthKey}-01`})); appState.finance.selectedMonth=newMonthKey; syncEcosystem('MONTH_CHANGED',{}); return {success:true}; }
function changeFinanceMonth(month){ appState.finance.selectedMonth=month; syncEcosystem('MONTH_CHANGED',{}); return {success:true}; }
function checkBudgetLimits(){ const m=ensureCurrentFinanceMonth(); const alerts=[]; m.budgets.forEach(b=>{ const used=m.expenses.filter(e=>e.category===b.category).reduce((s,e)=>s+Number(e.amount||0),0); b.used=used; b.remaining=Number(b.limit||0)-used; b.percentageUsed=b.limit>0?Math.round((used/b.limit)*100):0; if(used>b.limit) alerts.push({type:'budget_exceeded',category:b.category,message:`Hai superato il budget per ${b.category}`,used,limit:b.limit}); }); appState.budgetAlerts=alerts; return alerts; }
function addWorkout(workout){ if(!workout.name) return {success:false, errors:['Inserisci nome allenamento']}; const w={id:createId('workout'), name:workout.name, date:workout.date||appState.currentDate, time:workout.time||'', duration:Number(workout.duration||0), muscleGroup:workout.muscleGroup||'Generale', exercises:workout.exercises||[], notes:workout.notes||'', status:workout.status||'programmato'}; appState.workouts.push(w); if(workout.reminderEnabled&&w.date&&w.time) scheduleReminder('workout',w.id,'Allenamento',`${appState.user.name}, oggi hai ${w.name} alle ${w.time}`,w.date,w.time,'Fitness'); syncEcosystem('WORKOUT_ADDED',w); return {success:true,workout:w}; }
function editWorkout(workoutId, updatedData){ const w=appState.workouts.find(x=>x.id===workoutId); if(!w) return {success:false}; Object.assign(w,updatedData); syncEcosystem('WORKOUT_UPDATED',{}); return {success:true,workout:w}; }
function deleteWorkout(workoutId){ appState.workouts=appState.workouts.filter(w=>w.id!==workoutId); syncEcosystem('WORKOUT_DELETED',{}); return {success:true}; }
function addExerciseToWorkout(workoutId, exercise){ const w=appState.workouts.find(x=>x.id===workoutId); if(!w||!exercise.name) return {success:false}; const e={id:createId('exercise'), name:exercise.name, sets:Number(exercise.sets||0), reps:Number(exercise.reps||0), weight:Number(exercise.weight||0), restSeconds:Number(exercise.restSeconds||0), notes:exercise.notes||'', completed:false}; w.exercises.push(e); syncEcosystem('EXERCISE_ADDED',{}); return {success:true,exercise:e}; }
function editExercise(workoutId, exerciseId, updatedData){ const e=appState.workouts.find(w=>w.id===workoutId)?.exercises.find(x=>x.id===exerciseId); if(!e) return {success:false}; Object.assign(e,updatedData); ['sets','reps','weight','restSeconds'].forEach(k=>{ if(e[k]!==undefined) e[k]=Number(e[k]); }); syncEcosystem('EXERCISE_UPDATED',{}); return {success:true,exercise:e}; }
function deleteExercise(workoutId, exerciseId){ const w=appState.workouts.find(x=>x.id===workoutId); if(!w) return {success:false}; w.exercises=w.exercises.filter(e=>e.id!==exerciseId); syncEcosystem('EXERCISE_DELETED',{}); return {success:true}; }
function completeWorkout(workoutId){ const w=appState.workouts.find(x=>x.id===workoutId); if(!w) return {success:false}; w.status='completato'; syncEcosystem('WORKOUT_COMPLETED',{}); return {success:true}; }
function duplicateWorkout(workoutId,newDate){ const w=appState.workouts.find(x=>x.id===workoutId); if(!w) return {success:false}; const d=structuredClone(w); d.id=createId('workout'); d.date=newDate||appState.currentDate; d.status='programmato'; d.exercises=d.exercises.map(e=>({...e,id:createId('exercise'),completed:false})); appState.workouts.push(d); syncEcosystem('WORKOUT_DUPLICATED',{}); return {success:true,workout:d}; }
function calculateFitnessProgress(){ const completed=appState.workouts.filter(w=>w.status==='completato'); const totalVolume=completed.reduce((s,w)=>s+w.exercises.reduce((x,e)=>x+Number(e.sets||0)*Number(e.reps||0)*Number(e.weight||0),0),0); appState.fitnessSummary={totalWorkouts:appState.workouts.length,completedWorkouts:completed.length,totalVolume}; return appState.fitnessSummary; }
function addBloodPressure(systolic, diastolic, heartRate, date, time, note){ if(!systolic||!diastolic) return {success:false, errors:['Inserisci pressione sistolica e diastolica']}; const entry={id:createId('pressure'),systolic:Number(systolic),diastolic:Number(diastolic),heartRate:heartRate?Number(heartRate):null,date:date||appState.currentDate,time:time||'',note:note||''}; appState.health.bloodPressure.push(entry); syncEcosystem('BLOOD_PRESSURE_ADDED',entry); return {success:true,entry}; }
function addBodyTemperature(value,date,time,note){ if(!value) return {success:false, errors:['Inserisci temperatura']}; const entry={id:createId('temperature'),value:Number(value),unit:'°C',date:date||appState.currentDate,time:time||'',note:note||''}; appState.health.bodyTemperature.push(entry); syncEcosystem('BODY_TEMPERATURE_ADDED',entry); return {success:true,entry}; }
function addMedication(medication){ if(!medication.name) return {success:false}; const m={id:createId('medication'),name:medication.name,dosage:medication.dosage||'',frequency:medication.frequency||'',time:medication.time||'',startDate:medication.startDate||appState.currentDate,endDate:medication.endDate||null,notes:medication.notes||'',reminderEnabled:Boolean(medication.reminderEnabled)}; appState.health.medications.push(m); if(m.reminderEnabled&&m.time) scheduleReminder('medication',m.id,'Promemoria farmaco',`${appState.user.name}, ricordati di prendere ${m.dosage} di ${m.name}`,m.startDate,m.time,'Salute'); syncEcosystem('MEDICATION_ADDED',{}); return {success:true,medication:m}; }
function editMedication(medicationId, updatedData){ const m=appState.health.medications.find(x=>x.id===medicationId); if(!m) return {success:false}; Object.assign(m,updatedData); syncEcosystem('MEDICATION_UPDATED',{}); return {success:true,medication:m}; }
function deleteMedication(medicationId){ appState.health.medications=appState.health.medications.filter(m=>m.id!==medicationId); syncEcosystem('MEDICATION_DELETED',{}); return {success:true}; }
function addSupplement(supplement){ if(!supplement.name) return {success:false}; const s={id:createId('supplement'),name:supplement.name,dosage:supplement.dosage||'',frequency:supplement.frequency||'',time:supplement.time||'',startDate:supplement.startDate||appState.currentDate,endDate:supplement.endDate||null,notes:supplement.notes||'',reminderEnabled:Boolean(supplement.reminderEnabled)}; appState.health.supplements.push(s); if(s.reminderEnabled&&s.time) scheduleReminder('supplement',s.id,'Promemoria integratore',`${appState.user.name}, ricordati di prendere ${s.dosage} di ${s.name}`,s.startDate,s.time,'Salute'); syncEcosystem('SUPPLEMENT_ADDED',{}); return {success:true,supplement:s}; }
function editSupplement(supplementId, updatedData){ const s=appState.health.supplements.find(x=>x.id===supplementId); if(!s) return {success:false}; Object.assign(s,updatedData); syncEcosystem('SUPPLEMENT_UPDATED',{}); return {success:true,supplement:s}; }
function deleteSupplement(supplementId){ appState.health.supplements=appState.health.supplements.filter(s=>s.id!==supplementId); syncEcosystem('SUPPLEMENT_DELETED',{}); return {success:true}; }
function calculateHealthSummary(){ const lastPressure=appState.health.bloodPressure.at(-1)||null, lastTemperature=appState.health.bodyTemperature.at(-1)||null; appState.healthSummary={lastPressure,lastTemperature,medicationsCount:appState.health.medications.length,supplementsCount:appState.health.supplements.length}; return appState.healthSummary; }
function addNote(note){ if(!note.title&&!note.text) return {success:false}; const n={id:createId('note'),title:note.title||'Nota',text:note.text||'',category:note.category||'Generale',date:note.date||appState.currentDate,time:note.time||'',pinned:Boolean(note.pinned)}; appState.notes.push(n); syncEcosystem('NOTE_ADDED',n); return {success:true,note:n}; }
function editNote(noteId, updatedData){ const n=appState.notes.find(x=>x.id===noteId); if(!n) return {success:false}; Object.assign(n,updatedData); syncEcosystem('NOTE_UPDATED',{}); return {success:true,note:n}; }
function deleteNote(noteId){ appState.notes=appState.notes.filter(n=>n.id!==noteId); syncEcosystem('NOTE_DELETED',{}); return {success:true}; }
function getLatestNotes(limit=3){ return [...appState.notes].sort((a,b)=>`${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`)).slice(0,limit); }
function pinNote(noteId){ const n=appState.notes.find(x=>x.id===noteId); if(!n) return {success:false}; n.pinned=!n.pinned; syncEcosystem('NOTE_PINNED',{}); return {success:true,note:n}; }
function getWeatherIcon(condition){ const v=String(condition||'').toLowerCase(); if(v.includes('sole')) return 'sun'; if(v.includes('pioggia')) return 'rain'; if(v.includes('temporale')) return 'storm'; if(v.includes('neve')) return 'snow'; if(v.includes('vento')) return 'wind'; if(v.includes('nuvol')) return 'cloud'; return 'cloud'; }
function updateWeather(weatherData){ appState.weather={city:weatherData.city||'Posizione attuale', temperature:weatherData.temperature??null, condition:weatherData.condition||'Non disponibile', icon:getWeatherIcon(weatherData.condition), min:weatherData.min??null, max:weatherData.max??null, rainProbability:weatherData.rainProbability??null, wind:weatherData.wind??null, lastUpdated:new Date().toISOString()}; syncEcosystem('WEATHER_UPDATED',{}); return {success:true,weather:appState.weather}; }
function addNotification(notification){ if(!notification.title||!notification.date) return {success:false}; const n={id:createId('notification'),title:notification.title,message:notification.message||'',category:notification.category||'Generale',date:notification.date,time:notification.time||'',repeat:notification.repeat||'nessuna',status:'attiva',linkedEntityType:notification.linkedEntityType||'',linkedEntityId:notification.linkedEntityId||null}; appState.notifications.push(n); syncEcosystem('NOTIFICATION_ADDED',n); return {success:true,notification:n}; }
function editNotification(notificationId, updatedData){ const n=appState.notifications.find(x=>x.id===notificationId); if(!n) return {success:false}; Object.assign(n,updatedData); syncEcosystem('NOTIFICATION_UPDATED',{}); return {success:true,notification:n}; }
function deleteNotification(notificationId){ appState.notifications=appState.notifications.filter(n=>n.id!==notificationId); syncEcosystem('NOTIFICATION_DELETED',{}); return {success:true}; }
function markNotificationCompleted(notificationId){ const n=appState.notifications.find(x=>x.id===notificationId); if(!n) return {success:false}; n.status='completata'; syncEcosystem('NOTIFICATION_COMPLETED',{}); return {success:true}; }
function getTodayNotifications(){ return appState.notifications.filter(n=>n.date===appState.currentDate&&n.status==='attiva'); }
function scheduleReminder(entityType, entityId, title, message, date, time, category){ return addNotification({title,message,category,date,time,repeat:'nessuna',linkedEntityType:entityType,linkedEntityId:entityId}); }
function requestHealthPermissions(){ return {success:true,message:'Richiedi autorizzazione utente per accedere ai dati Apple Health'}; }
function connectAppleHealth(){ appState.appleHealth={connected:true,lastSync:null,permissions:{steps:true,activeCalories:true,heartRate:true,workouts:true,sleep:true,weight:true,height:true}}; syncEcosystem('APPLE_HEALTH_CONNECTED',{}); return {success:true,message:'Apple Health collegato in modalità mock. In React Native collegare HealthKit.'}; }
function disconnectAppleHealth(){ appState.appleHealth={connected:false,lastSync:null,permissions:{}}; syncEcosystem('APPLE_HEALTH_DISCONNECTED',{}); return {success:true}; }
function syncHealthData(){ if(!appState.appleHealth?.connected) return {success:false, errors:['Apple Health non collegato']}; appState.appleHealth.lastSync=new Date().toISOString(); appState.appleHealthSummary={stepsToday:0,activeCalories:0,heartRateAverage:null,lastWorkout:null,sleepHours:null}; syncEcosystem('APPLE_HEALTH_SYNCED',{}); return {success:true,data:appState.appleHealthSummary}; }
function getHealthSummaryFromAppleHealth(){ return appState.appleHealthSummary || {stepsToday:0,activeCalories:0,heartRateAverage:null,lastWorkout:null,sleepHours:null}; }
function countPlannedMeals(){ return ['breakfast','lunch','dinner','snack'].filter(k=>appState.dailyMeals[k]).length; }
function generateSmartNotifications(){ const smart=[]; if(getTodayNotifications().length>0) smart.push({type:'today_notifications',message:`${appState.user.name}, hai ${getTodayNotifications().length} promemoria attivi oggi.`,action:'Vedi notifiche'}); const w=appState.workouts.find(x=>x.date===appState.currentDate&&x.status==='programmato'); if(w) smart.push({type:'today_workout',message:`${appState.user.name}, oggi hai l’allenamento: ${w.name}.`,action:'Apri allenamenti'}); if(!appState.health.bloodPressure.at(-1)) smart.push({type:'missing_pressure',message:'Non hai ancora inserito una misurazione della pressione.',action:'Aggiungi pressione'}); return smart; }
function generateSuggestions(){ const suggestions=[]; const missingPrices=appState.shoppingList.filter(i=>i.estimatedPrice===null&&i.realPrice===null); if(missingPrices.length) suggestions.push({type:'missing_price',message:`Hai ${missingPrices.length} prodotti senza prezzo. Vuoi aggiungerli?`,action:'Aggiungi prezzi'}); const notPurchased=appState.shoppingList.filter(i=>!i.purchased); if(notPurchased.length) suggestions.push({type:'shopping_remaining',message:`Ti mancano ${notPurchased.length} prodotti da comprare.`,action:'Apri lista spesa'}); const fs=calculateFinanceSummary(); if(fs.expectedSavings<0) suggestions.push({type:'negative_savings',message:'Il risparmio previsto è negativo. Controlla le uscite.',action:'Vedi finanza'}); if(fs.savingGoalDelta<0) suggestions.push({type:'saving_goal_not_reached',message:`Sei sotto l’obiettivo di risparmio di €${Math.abs(fs.savingGoalDelta).toFixed(2)}.`,action:'Controlla budget'}); if(ensureCurrentFinanceMonth().budgets.length===0) suggestions.push({type:'missing_budget',message:'Non hai ancora impostato un budget per questo mese.',action:'Imposta budget'}); const todayWorkout=appState.workouts.find(w=>w.date===appState.currentDate&&w.status==='programmato'); if(todayWorkout) suggestions.push({type:'today_workout',message:`${appState.user.name}, oggi hai l’allenamento: ${todayWorkout.name}.`,action:'Apri allenamenti'}); if(!appState.health.bloodPressure.at(-1)) suggestions.push({type:'missing_pressure',message:'Non hai ancora inserito una misurazione della pressione.',action:'Aggiungi pressione'}); if(appState.weather.condition?.toLowerCase().includes('pioggia')) suggestions.push({type:'weather_indoor',message:'Oggi potrebbe piovere. Valuta un allenamento indoor.',action:'Apri allenamenti'}); appState.suggestions=suggestions; return suggestions; }
function generateDashboardWidgets(){ const f=calculateFinanceSummary(), s=recalculateShoppingTotals(), fit=calculateFitnessProgress(), h=calculateHealthSummary(), latest=getLatestNotes(1)[0], todayWorkout=appState.workouts.find(w=>w.date===appState.currentDate&&w.status==='programmato'); return [
 {id:'welcome_armand',title:`Ciao ${appState.user.name}`,mainValue:'Riepilogo di oggi',description:'Pasti, allenamenti, salute, finanza e notifiche',dataSource:'Dati personali, agenda, pasti, allenamenti e finanza',actionButton:'Vedi giornata',screen:'dashboard',icon:'sparkles'},
 {id:'daily_meals',title:'Cosa mangio oggi',mainValue:countPlannedMeals()+' pasti pianificati',description:'Pasti impostati per oggi',dataSource:'Piano alimentare giornaliero',actionButton:'Vedi pasti',screen:'meals',icon:'salad'},
 {id:'shopping_list',title:'Lista della spesa',mainValue:s.notPurchasedItems+' prodotti da comprare',description:s.totalItems+' prodotti totali',dataSource:'Ricette di oggi + prodotti manuali',actionButton:'Apri lista',screen:'shopping',icon:'cart'},
 {id:'finance_progress',title:'Progressi finanza',mainValue:'€'+f.availableBalance.toFixed(2),description:'Saldo disponibile e obiettivo risparmio',dataSource:'Entrate, uscite, budget e obiettivo risparmio',actionButton:'Vedi finanza',screen:'finance',icon:'wallet'},
 {id:'budget_available',title:'Budget disponibile',mainValue:'€'+f.availableBalance.toFixed(2),description:'Saldo disponibile mensile',dataSource:'Entrate e uscite del mese',actionButton:'Modifica budget',screen:'finance',icon:'euro'},
 {id:'expected_savings',title:'Risparmio previsto',mainValue:'€'+f.expectedSavings.toFixed(2),description:'Differenza obiettivo: €'+f.savingGoalDelta.toFixed(2),dataSource:'Budget mensile + obiettivo risparmio',actionButton:'Vedi finanza',screen:'finance',icon:'wallet'},
 {id:'estimated_shopping',title:'Spesa stimata',mainValue:'€'+s.estimatedTotal.toFixed(2),description:'Costo stimato lista spesa',dataSource:'Lista della spesa + prezzi stimati inseriti',actionButton:'Modifica prezzi',screen:'shopping',icon:'cart'},
 {id:'real_shopping',title:'Spesa reale',mainValue:'€'+s.realTotal.toFixed(2),description:'Costo reale prodotti acquistati',dataSource:'Prezzi reali inseriti nella lista spesa',actionButton:'Vedi spesa',screen:'shopping',icon:'receipt'},
 {id:'workout_today',title:'Allenamento',mainValue:todayWorkout?.name||'Nessun allenamento oggi',description:`${fit.completedWorkouts} allenamenti completati`,dataSource:'Lista allenamenti',actionButton:'Apri allenamenti',screen:'workouts',icon:'dumbbell'},
 {id:'health',title:'Salute',mainValue:h.lastPressure?`${h.lastPressure.systolic}/${h.lastPressure.diastolic}`:'Nessuna pressione inserita',description:'Pressione, temperatura, farmaci e integratori',dataSource:'Misurazioni salute, farmaci e integratori',actionButton:'Apri salute',screen:'health',icon:'heart'},
 {id:'latest_notes',title:'Ultime note',mainValue:getLatestNotes(3).length+' note recenti',description:latest?.title||'Nessuna nota recente',dataSource:'Note personali',actionButton:'Apri note',screen:'notes',icon:'note'},
 {id:'weather',title:'Meteo',mainValue:appState.weather.temperature!==null?appState.weather.temperature+'°C':'Non disponibile',description:appState.weather.condition,dataSource:'Servizio meteo / posizione utente',icon:appState.weather.icon,actionButton:'Vedi meteo',screen:'weather'},
 {id:'notifications',title:'Promemoria',mainValue:getTodayNotifications().length+' oggi',description:'Scadenze, farmaci, finanza e allenamenti',dataSource:'Scadenze, farmaci, finanza, allenamenti',actionButton:'Vedi promemoria',screen:'notifications',icon:'bell'},
 {id:'smart_suggestions',title:'Suggerimenti',mainValue:appState.suggestions.length+' attivi',description:'Azioni consigliate dal sistema',dataSource:'Analisi automatica di pasti, spesa, finanza, allenamenti e salute',actionButton:'Vedi suggerimenti',screen:'suggestions',icon:'sparkles'}
]; }
function updateWidgets(){ appState.widgets=generateDashboardWidgets(); return appState.widgets; }
function getQuickAddOptions(currentScreen){ return ({dashboard:['Aggiungi prodotto','Aggiungi ricetta','Aggiungi entrata','Aggiungi uscita','Aggiungi allenamento','Aggiungi pressione','Aggiungi temperatura','Aggiungi nota','Aggiungi promemoria'],shopping:['Aggiungi prodotto','Importa ingredienti da ricetta','Crea categoria'],finance:['Aggiungi entrata','Aggiungi uscita','Aggiungi budget','Aggiungi obiettivo risparmio','Aggiungi promemoria pagamento'],recipes:['Aggiungi ricetta','Aggiungi pasto al giorno','Aggiungi ingrediente'],workouts:['Aggiungi allenamento','Aggiungi esercizio','Aggiungi serie','Aggiungi nota allenamento','Duplica allenamento precedente'],health:['Aggiungi pressione','Aggiungi temperatura','Aggiungi farmaco','Aggiungi integratore'],notes:['Aggiungi nota','Fissa nota importante'],notifications:['Aggiungi promemoria','Vedi promemoria di oggi']})[currentScreen] || ['Aggiungi prodotto','Aggiungi nota']; }
function syncEcosystem(eventType,payload={}){ if(['RECIPE_ADDED','RECIPE_UPDATED','RECIPE_DELETED','RECIPE_ASSIGNED_TO_MEAL','MEAL_CHANGED'].includes(eventType)) generateShoppingListFromDailyMeals(); if(['SHOPPING_ITEM_PURCHASED','REAL_PRICE_ADDED'].includes(eventType)) updateFoodExpenseFromShopping(); recalculateShoppingTotals(); updateFinanceSummary(); checkBudgetLimits(); calculateFitnessProgress(); calculateHealthSummary(); generateSuggestions(); appState.suggestions=[...generateSuggestions(), ...generateSmartNotifications()].filter((v,i,a)=>a.findIndex(x=>x.type===v.type)===i); updateWidgets(); saveState(); return {widgets:appState.widgets,suggestions:appState.suggestions,shoppingSummary:appState.shoppingSummary,financeSummary:appState.financeSummary,fitnessSummary:appState.fitnessSummary,healthSummary:appState.healthSummary}; }
function bootstrap(){ ensureCurrentFinanceMonth(); if(!appState.dailyMeals.breakfast) appState.dailyMeals.breakfast={name:'Yogurt con frutta', recipeId:'recipe_demo_2'}; if(!appState.dailyMeals.lunch) appState.dailyMeals.lunch={name:'Pasta integrale con tonno', recipeId:'recipe_demo_1'}; generateShoppingListFromDailyMeals(); ensureCurrentFinanceMonth().savingGoal ||= 250; if(!ensureCurrentFinanceMonth().budgets.length) addOrUpdateBudget('Spesa alimentare',250); recalculateShoppingTotals(); updateFinanceSummary(); checkBudgetLimits(); calculateFitnessProgress(); calculateHealthSummary(); generateSuggestions(); generateSmartNotifications(); updateWidgets(); saveState(); }

const Icon = ({name}) => { const map={sun:Sun,cloud:Cloud,rain:CloudRain,storm:Zap,snow:CloudSnow,wind:Wind,salad:Salad,cart:ShoppingCart,wallet:Wallet,euro:Euro,dumbbell:Dumbbell,heart:HeartPulse,note:NotebookText,bell:Bell,sparkles:Sparkles,receipt:ReceiptText}; const C=map[name]||Sparkles; return <C size={20}/>; };
const euro = n => '€' + Number(n||0).toFixed(2);
function Field({label, children}){ return <label className="field"><span>{label}</span>{children}</label>; }
function Card({children,className=''}){ return <div className={'card '+className}>{children}</div>; }
function Widget({w,onGo}){ return <button className="widget" onClick={()=>onGo(w.screen)}><div className="widgetIcon"><Icon name={w.icon}/></div><div className="widgetText"><h3>{w.title}</h3><strong>{w.mainValue}</strong><p>{w.description}</p><small>Fonte input: {w.dataSource}</small></div><span className="cta">{w.actionButton}<ChevronRight size={15}/></span></button>; }
function SectionTitle({title,subtitle}){ return <div className="sectionTitle"><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>; }

function App(){
 const [,force]=useState(0); const [screen,setScreenState]=useState('dashboard'); const [quick,setQuick]=useState(false);
 const state=appState; const refresh=()=>force(x=>x+1); const setScreen=s=>{ appState.currentScreen=s; setScreenState(s); saveState(); };
 useEffect(()=>{ loadState(); refresh(); },[]);
 const actions={refresh,setScreen, addManualShoppingItem:(...a)=>{addManualShoppingItem(...a);refresh();}, togglePurchasedItem:(id)=>{togglePurchasedItem(id);refresh();}, updateEstimatedPrice:(...a)=>{updateEstimatedPrice(...a);refresh();}, updateRealPrice:(...a)=>{updateRealPrice(...a);refresh();}, deleteShoppingItem:(id)=>{deleteShoppingItem(id);refresh();}, addIncome:(...a)=>{addIncome(...a);refresh();}, addExpense:(...a)=>{addExpense(...a);refresh();}, addBudget:(...a)=>{addOrUpdateBudget(...a);refresh();}, addWorkout:(w)=>{addWorkout(w);refresh();}, addExercise:(...a)=>{addExerciseToWorkout(...a);refresh();}, completeWorkout:(id)=>{completeWorkout(id);refresh();}, editExercise:(...a)=>{editExercise(...a);refresh();}, addPressure:(...a)=>{addBloodPressure(...a);refresh();}, addTemp:(...a)=>{addBodyTemperature(...a);refresh();}, addMedication:(m)=>{addMedication(m);refresh();}, addSupplement:(s)=>{addSupplement(s);refresh();}, addNote:(n)=>{addNote(n);refresh();}, pinNote:(id)=>{pinNote(id);refresh();}, deleteNote:(id)=>{deleteNote(id);refresh();}, addNotification:(n)=>{addNotification(n);refresh();}, completeNotification:(id)=>{markNotificationCompleted(id);refresh();}, assignRecipe:(meal,id)=>{assignRecipeToMeal(meal,id);refresh();}, addRecipe:(r)=>{addRecipe(r);refresh();}, connectHealth:()=>{connectAppleHealth();refresh();}, disconnectHealth:()=>{disconnectAppleHealth();refresh();}, updateWeather:(w)=>{updateWeather(w);refresh();}, reset:()=>{localStorage.removeItem(STORAGE_KEY); appState=structuredClone(starterState); bootstrap(); refresh();}};
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">A</div><div><b>Armand OS</b><small>Ecosistema personale</small></div></div><nav>{SECTIONS.map(([id,label,NavIcon])=><button key={id} onClick={()=>setScreen(id)} className={screen===id?'active':''}><NavIcon size={17}/>{label}</button>)}</nav></aside><main><TopBar state={state}/><Screen screen={screen} state={state} actions={actions}/></main><BottomNav screen={screen} setScreen={setScreen}/><button className="fab" onClick={()=>setQuick(!quick)}><Plus/></button>{quick&&<QuickMenu screen={screen} setScreen={setScreen} close={()=>setQuick(false)}/>}</div>;
}
function TopBar({state}){ return <header className="top"><div><p>{new Date(state.currentDate).toLocaleDateString('it-IT',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</p><h1>Ciao {state.user.name}</h1></div><div className="pill"><Bell size={16}/>{getTodayNotifications().length} promemoria oggi</div></header>; }
function BottomNav({screen,setScreen}){ const items=[['dashboard','Home',Home],['shopping','Spesa',ShoppingCart],['finance','Finanza',Wallet],['health','Salute',HeartPulse],['notes','Note',NotebookText]]; return <div className="bottomNav">{items.map(([id,l,I])=><button className={screen===id?'active':''} onClick={()=>setScreen(id)} key={id}><I size={20}/><span>{l}</span></button>)}</div>; }
function QuickMenu({screen,setScreen,close}){ return <div className="quick"><h3>Aggiunta rapida</h3>{getQuickAddOptions(screen).map(o=><button key={o} onClick={()=>{ const map={'Aggiungi prodotto':'shopping','Aggiungi ricetta':'recipes','Aggiungi entrata':'finance','Aggiungi uscita':'finance','Aggiungi budget':'finance','Aggiungi obiettivo risparmio':'finance','Aggiungi allenamento':'workouts','Aggiungi esercizio':'workouts','Aggiungi pressione':'pressure','Aggiungi temperatura':'temperature','Aggiungi farmaco':'medications','Aggiungi integratore':'supplements','Aggiungi nota':'notes','Aggiungi promemoria':'notifications'}; setScreen(map[o]||screen); close(); }}>{o}</button>)}</div>; }
function Screen({screen,state,actions}){ const map={dashboard:Dashboard,meals:Meals,recipes:Recipes,shopping:Shopping,finance:Finance,workouts:Workouts,exercises:Exercises,fitness:Fitness,health:Health,pressure:Pressure,temperature:Temperature,medications:Medications,supplements:Supplements,notes:Notes,weather:Weather,notifications:Notifications,suggestions:Suggestions,settings:SettingsPage}; const C=map[screen]||Dashboard; return <C state={state} actions={actions}/>; }
function Dashboard({state,actions}){ const cards=[['Cosa mangio oggi',countPlannedMeals()+' pasti','Piano alimentare giornaliero','meals',Salad],['Lista della spesa',state.shoppingSummary?.notPurchasedItems+' mancanti','Ricette di oggi + manuali','shopping',ShoppingCart],['Ricette del giorno',countPlannedMeals()+' ricette','Pasti assegnati','recipes',ReceiptText],['Budget mensile',euro(state.financeSummary?.availableBalance),'Entrate e uscite mese','finance',Wallet],['Entrate del mese',euro(state.financeSummary?.totalIncome),'Finanza mese corrente','finance',Euro],['Uscite del mese',euro(state.financeSummary?.totalExpenses),'Finanza mese corrente','finance',Euro],['Risparmio previsto',euro(state.financeSummary?.expectedSavings),'Budget + obiettivo','finance',Wallet],['Allenamento di oggi',state.workouts.find(w=>w.date===state.currentDate)?.name||'Nessuno','Lista allenamenti','workouts',Dumbbell],['Progressi fitness',(state.fitnessSummary?.completedWorkouts||0)+' completati','Allenamenti completati','fitness',HeartPulse],['Salute',state.healthSummary?.lastPressure?`${state.healthSummary.lastPressure.systolic}/${state.healthSummary.lastPressure.diastolic}`:'Da aggiornare','Misurazioni salute','health',HeartPulse],['Pressione',state.healthSummary?.lastPressure?'Ultima inserita':'Nessun dato','Storico pressione','pressure',HeartPulse],['Temperatura',state.healthSummary?.lastTemperature?state.healthSummary.lastTemperature.value+'°C':'Nessun dato','Storico temperatura','temperature',Thermometer],['Farmaci',state.health.medications.length+' attivi','Farmaci inseriti','medications',Pill],['Integratori',state.health.supplements.length+' attivi','Integratori inseriti','supplements',Apple],['Ultime note',getLatestNotes(3).length+' note','Note personali','notes',NotebookText],['Meteo',state.weather.temperature+'°C '+state.weather.condition,'Servizio meteo / posizione','weather',Cloud],['Promemoria',getTodayNotifications().length+' oggi','Notifiche attive','notifications',Bell],['Suggerimenti intelligenti',state.suggestions.length+' attivi','Analisi automatica dati','suggestions',Sparkles],['Aggiunta rapida','+','Menu contestuale','dashboard',Plus]]; return <><SectionTitle title="Dashboard" subtitle="Armand, cosa devi fare, mangiare, controllare e ricordare oggi?"/><div className="widgetGrid">{state.widgets.map(w=><Widget key={w.id} w={w} onGo={actions.setScreen}/>)}</div><SectionTitle title="Card operative"/><div className="cardGrid">{cards.map(([t,v,src,go,I])=><button className="opCard" key={t} onClick={()=>actions.setScreen(go)}><I size={21}/><h3>{t}</h3><strong>{v}</strong><p>Stato: aggiornato</p><small>{src}</small><span>Apri sezione</span></button>)}</div></>; }
function Meals({state,actions}){ const labels={breakfast:'Colazione',lunch:'Pranzo',dinner:'Cena',snack:'Snack'}; return <><SectionTitle title="Pasti di oggi" subtitle="Ricette, ingredienti, preparazione e lista spesa collegata."/><div className="grid2">{Object.entries(labels).map(([k,label])=>{ const meal=state.dailyMeals[k]; const recipe=state.recipes.find(r=>r.id===meal?.recipeId); return <Card key={k}><h3>{label}</h3><select value={meal?.recipeId||''} onChange={e=>actions.assignRecipe(k,e.target.value)}><option value="">Scegli ricetta</option>{state.recipes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>{recipe?<><h2>{recipe.name}</h2><p><Timer size={15}/> {recipe.prepTime} minuti</p><small>Fonte input: Ricette assegnate al piano alimentare giornaliero</small><ul>{recipe.ingredients.map(i=><li key={i.name}>{i.quantity} {i.unit} {i.name}</li>)}</ul><p>{recipe.steps?.slice(0,2).join(' → ')}</p></>:<p>Nessuna ricetta assegnata.</p>}</Card>})}</div></>; }
function Recipes({state,actions}){ const [name,setName]=useState(''); return <><SectionTitle title="Ricette" subtitle="Aggiungi, assegna ai pasti e genera automaticamente la spesa senza duplicati."/><Card><h3>Nuova ricetta rapida</h3><div className="row"><input placeholder="Nome ricetta" value={name} onChange={e=>setName(e.target.value)}/><button onClick={()=>{actions.addRecipe({name,mealType:'altro',prepTime:10,ingredients:[{name:'Ingrediente',quantity:1,unit:'pz',category:'Altro',estimatedPrice:0}],steps:['Preparazione breve']});setName('')}}>Aggiungi</button></div><small>Potrai modificare ingredienti nel codice o estendere il form.</small></Card><div className="grid2">{state.recipes.map(r=><Card key={r.id}><h3>{r.name}</h3><p>{r.mealType} · {r.prepTime} min</p><small>Fonte input: archivio ricette locale</small><ul>{r.ingredients.map(i=><li key={i.name}>{i.quantity} {i.unit} {i.name} — {i.category}</li>)}</ul></Card>)}</div></>; }
function Shopping({state,actions}){ const [form,setForm]=useState({name:'',quantity:1,unit:'pz',category:'Altro',price:''}); const byCat=SHOPPING_CATEGORIES.map(c=>[c,state.shoppingList.filter(i=>i.category===c)]).filter(([,arr])=>arr.length); return <><SectionTitle title="Lista della spesa" subtitle={`Stimato ${euro(state.shoppingSummary?.estimatedTotal)} · Reale ${euro(state.shoppingSummary?.realTotal)} · Fonte: ricette di oggi + prodotti manuali`}/><Card><h3>Aggiungi prodotto manuale</h3><div className="formGrid"><input placeholder="Prodotto" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{SHOPPING_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><input type="number" placeholder="Prezzo stimato" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><button onClick={()=>{actions.addManualShoppingItem(form.name,form.quantity,form.unit,form.category,form.price);setForm({...form,name:'',price:''});}}>Aggiungi</button></div></Card>{byCat.map(([cat,items])=><Card key={cat}><h3>{cat}</h3>{items.map(i=><div className="item" key={i.id}><input type="checkbox" checked={i.purchased} onChange={()=>actions.togglePurchasedItem(i.id)}/><div><b className={i.purchased?'done':''}>{i.name}</b><small>{i.quantity} {i.unit} · Fonte: {i.source}</small><small>Prezzo stimato <input type="number" value={i.estimatedPrice??''} onChange={e=>actions.updateEstimatedPrice(i.id,e.target.value)} /> Reale <input type="number" value={i.realPrice??''} onChange={e=>actions.updateRealPrice(i.id,e.target.value)} /></small></div><button className="ghost" onClick={()=>actions.deleteShoppingItem(i.id)}>Elimina</button></div>)}</Card>)}</>; }
function Finance({state,actions}){ const m=ensureCurrentFinanceMonth(); const [entry,setEntry]=useState({name:'',amount:'',category:'Extra',kind:'uscita',date:state.currentDate,reminder:false}); return <><SectionTitle title="Finanza" subtitle={`Mese ${state.finance.selectedMonth} · Saldo ${euro(state.financeSummary?.availableBalance)} · Risparmio previsto ${euro(state.financeSummary?.expectedSavings)}`}/><Card><h3>Nuovo movimento</h3><div className="formGrid"><input type="month" value={state.finance.selectedMonth} onChange={e=>{changeFinanceMonth(e.target.value);actions.refresh();}}/><select value={entry.kind} onChange={e=>setEntry({...entry,kind:e.target.value})}><option>uscita</option><option>entrata</option></select><input placeholder="Nome" value={entry.name} onChange={e=>setEntry({...entry,name:e.target.value})}/><input type="number" placeholder="Importo" value={entry.amount} onChange={e=>setEntry({...entry,amount:e.target.value})}/><select value={entry.category} onChange={e=>setEntry({...entry,category:e.target.value})}>{FINANCE_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><input type="date" value={entry.date} onChange={e=>setEntry({...entry,date:e.target.value})}/><button onClick={()=>{entry.kind==='entrata'?actions.addIncome(entry.name,entry.amount,'variable',entry.date):actions.addExpense(entry.name,entry.amount,entry.category,'variable',entry.date);setEntry({...entry,name:'',amount:''})}}>Salva</button></div><small>Fonte input: entrate, uscite, budget, obiettivo risparmio e spesa reale acquistata.</small></Card><div className="grid3"><Card><h3>Entrate</h3><h2>{euro(state.financeSummary?.totalIncome)}</h2></Card><Card><h3>Uscite</h3><h2>{euro(state.financeSummary?.totalExpenses)}</h2></Card><Card><h3>Obiettivo</h3><input type="number" value={m.savingGoal} onChange={e=>{m.savingGoal=Number(e.target.value);syncEcosystem('BUDGET_CHANGED');actions.refresh();}}/></Card></div><Card><h3>Budget categoria</h3><div className="formGrid"><select id="budgetCat">{FINANCE_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><input id="budgetLimit" type="number" placeholder="Limite"/><button onClick={()=>actions.addBudget(document.getElementById('budgetCat').value,document.getElementById('budgetLimit').value)}>Salva budget</button></div>{m.budgets.map(b=><p key={b.category}>{b.category}: {euro(b.used)} / {euro(b.limit)} — {b.percentageUsed}%</p>)}{state.budgetAlerts.map(a=><p className="alert" key={a.category}>{a.message}</p>)}</Card><div className="grid2"><Card><h3>Entrate</h3>{m.incomes.map(i=><p key={i.id}>{i.date} · {i.name} · {euro(i.amount)}</p>)}</Card><Card><h3>Uscite</h3>{m.expenses.map(e=><p key={e.id}>{e.date} · {e.name} · {euro(e.amount)} {e.automatic?'· automatico':''}</p>)}</Card></div></>; }
function Workouts({state,actions}){ const [w,setW]=useState({name:'',date:state.currentDate,time:'18:00',duration:45,muscleGroup:'Generale'}); return <><SectionTitle title="Allenamenti" subtitle="Programma, modifica esercizi, completa e calcola volume totale."/><Card><h3>Nuovo allenamento</h3><div className="formGrid"><input placeholder="Nome" value={w.name} onChange={e=>setW({...w,name:e.target.value})}/><input type="date" value={w.date} onChange={e=>setW({...w,date:e.target.value})}/><input type="time" value={w.time} onChange={e=>setW({...w,time:e.target.value})}/><input type="number" value={w.duration} onChange={e=>setW({...w,duration:e.target.value})}/><input value={w.muscleGroup} onChange={e=>setW({...w,muscleGroup:e.target.value})}/><button onClick={()=>{actions.addWorkout({...w,reminderEnabled:true});setW({...w,name:''});}}>Aggiungi</button></div></Card>{state.workouts.map(workout=><WorkoutCard key={workout.id} workout={workout} actions={actions}/>)}</>; }
function WorkoutCard({workout,actions}){ const [e,setE]=useState({name:'',sets:3,reps:10,weight:0,restSeconds:60}); return <Card><h3>{workout.name}</h3><p>{workout.date} {workout.time} · {workout.duration} min · {workout.muscleGroup} · Stato: {workout.status}</p><small>Fonte input: lista allenamenti ed esercizi modificabili</small>{workout.exercises.map(ex=><div className="item" key={ex.id}><input type="checkbox" checked={ex.completed} onChange={()=>actions.editExercise(workout.id,ex.id,{completed:!ex.completed})}/><div><b>{ex.name}</b><small>Serie <input type="number" value={ex.sets} onChange={ev=>actions.editExercise(workout.id,ex.id,{sets:ev.target.value})}/> Rip <input type="number" value={ex.reps} onChange={ev=>actions.editExercise(workout.id,ex.id,{reps:ev.target.value})}/> Peso <input type="number" value={ex.weight} onChange={ev=>actions.editExercise(workout.id,ex.id,{weight:ev.target.value})}/> kg</small></div></div>)}<div className="formGrid"><input placeholder="Esercizio" value={e.name} onChange={ev=>setE({...e,name:ev.target.value})}/><input type="number" value={e.sets} onChange={ev=>setE({...e,sets:ev.target.value})}/><input type="number" value={e.reps} onChange={ev=>setE({...e,reps:ev.target.value})}/><input type="number" value={e.weight} onChange={ev=>setE({...e,weight:ev.target.value})}/><button onClick={()=>{actions.addExercise(workout.id,e);setE({...e,name:''})}}>Aggiungi esercizio</button><button onClick={()=>actions.completeWorkout(workout.id)}>Completa allenamento</button></div></Card>; }
function Exercises({state}){ return <><SectionTitle title="Esercizi" subtitle="Tutti gli esercizi sono modificabili dentro ogni allenamento."/>{state.workouts.flatMap(w=>w.exercises.map(e=><Card key={w.id+e.id}><h3>{e.name}</h3><p>{w.name}: {e.sets} serie · {e.reps} rip · {e.weight} kg · recupero {e.restSeconds}s</p><small>Fonte input: allenamenti programmati</small></Card>))}</>; }
function Fitness({state,actions}){ const h=getHealthSummaryFromAppleHealth(); return <><SectionTitle title="Fitness" subtitle="Progressi, volume e predisposizione Apple Health."/><div className="grid3"><Card><h3>Allenamenti</h3><h2>{state.fitnessSummary?.completedWorkouts}/{state.fitnessSummary?.totalWorkouts}</h2><small>Fonte input: allenamenti completati</small></Card><Card><h3>Volume totale</h3><h2>{state.fitnessSummary?.totalVolume} kg</h2><small>Fonte input: serie × ripetizioni × peso</small></Card><Card><h3>Apple Health</h3><h2>{state.appleHealth.connected?'Collegato':'Non collegato'}</h2><button onClick={state.appleHealth.connected?actions.disconnectHealth:actions.connectHealth}>{state.appleHealth.connected?'Scollega':'Collega mock'}</button></Card></div><Card><h3>Dati Health predisposti</h3><p>Passi: {h.stepsToday}, calorie attive: {h.activeCalories}, cuore medio: {h.heartRateAverage||'n/d'}</p><small>Fonte input: HealthKit / Apple Health con consenso utente. In web è mock; in React Native collegare react-native-health o HealthKit.</small></Card></>; }
function Health({state}){ return <><SectionTitle title="Salute" subtitle="Pressione, temperatura, farmaci, integratori e storico."/><div className="grid2"><Card><h3>Ultima pressione</h3><h2>{state.healthSummary?.lastPressure?`${state.healthSummary.lastPressure.systolic}/${state.healthSummary.lastPressure.diastolic}`:'Nessuna'}</h2><small>Fonte input: misurazioni pressione manuali</small></Card><Card><h3>Ultima temperatura</h3><h2>{state.healthSummary?.lastTemperature?state.healthSummary.lastTemperature.value+'°C':'Nessuna'}</h2><small>Fonte input: misurazioni temperatura manuali</small></Card><Card><h3>Farmaci</h3><h2>{state.health.medications.length}</h2><small>Fonte input: farmaci inseriti</small></Card><Card><h3>Integratori</h3><h2>{state.health.supplements.length}</h2><small>Fonte input: integratori inseriti</small></Card></div></>; }
function Pressure({state,actions}){ const [p,setP]=useState({sys:120,dia:80,hr:72,date:state.currentDate,time:'08:30',note:''}); return <><SectionTitle title="Pressione"/><Card><div className="formGrid"><input type="number" value={p.sys} onChange={e=>setP({...p,sys:e.target.value})}/><input type="number" value={p.dia} onChange={e=>setP({...p,dia:e.target.value})}/><input type="number" value={p.hr} onChange={e=>setP({...p,hr:e.target.value})}/><input type="date" value={p.date} onChange={e=>setP({...p,date:e.target.value})}/><input type="time" value={p.time} onChange={e=>setP({...p,time:e.target.value})}/><input placeholder="Nota" value={p.note} onChange={e=>setP({...p,note:e.target.value})}/><button onClick={()=>actions.addPressure(p.sys,p.dia,p.hr,p.date,p.time,p.note)}>Salva pressione</button></div></Card>{state.health.bloodPressure.slice().reverse().map(x=><Card key={x.id}><h3>{x.systolic}/{x.diastolic}</h3><p>{x.heartRate||'-'} bpm · {x.date} {x.time}</p><small>Fonte input: inserimento manuale pressione</small></Card>)}</>; }
function Temperature({state,actions}){ const [t,setT]=useState({value:36.7,date:state.currentDate,time:'08:45',note:''}); return <><SectionTitle title="Temperatura corporea"/><Card><div className="formGrid"><input type="number" step="0.1" value={t.value} onChange={e=>setT({...t,value:e.target.value})}/><input type="date" value={t.date} onChange={e=>setT({...t,date:e.target.value})}/><input type="time" value={t.time} onChange={e=>setT({...t,time:e.target.value})}/><input placeholder="Nota" value={t.note} onChange={e=>setT({...t,note:e.target.value})}/><button onClick={()=>actions.addTemp(t.value,t.date,t.time,t.note)}>Salva temperatura</button></div></Card>{state.health.bodyTemperature.slice().reverse().map(x=><Card key={x.id}><h3>{x.value} °C</h3><p>{x.date} {x.time} · {x.note}</p><small>Fonte input: inserimento manuale temperatura</small></Card>)}</>; }
function Medications({state,actions}){ return <MedicationLike title="Farmaci" items={state.health.medications} add={actions.addMedication} source="farmaci inseriti e promemoria salute"/>; }
function Supplements({state,actions}){ return <MedicationLike title="Integratori" items={state.health.supplements} add={actions.addSupplement} source="integratori inseriti e promemoria salute"/>; }
function MedicationLike({title,items,add,source}){ const [m,setM]=useState({name:'',dosage:'',frequency:'giornaliera',time:'09:00',reminderEnabled:true}); return <><SectionTitle title={title}/><Card><div className="formGrid"><input placeholder="Nome" value={m.name} onChange={e=>setM({...m,name:e.target.value})}/><input placeholder="Dosaggio" value={m.dosage} onChange={e=>setM({...m,dosage:e.target.value})}/><input value={m.frequency} onChange={e=>setM({...m,frequency:e.target.value})}/><input type="time" value={m.time} onChange={e=>setM({...m,time:e.target.value})}/><button onClick={()=>{add(m);setM({...m,name:'',dosage:''})}}>Aggiungi</button></div></Card>{items.map(x=><Card key={x.id}><h3>{x.name}</h3><p>{x.dosage} · {x.frequency} · {x.time}</p><small>Fonte input: {source}</small></Card>)}</>; }
function Notes({state,actions}){ const [n,setN]=useState({title:'',text:'',category:'Generale',pinned:false}); return <><SectionTitle title="Note personali"/><Card><div className="formGrid"><input placeholder="Titolo" value={n.title} onChange={e=>setN({...n,title:e.target.value})}/><select value={n.category} onChange={e=>setN({...n,category:e.target.value})}>{['Generale','Salute','Allenamento','Finanza','Alimentazione','Promemoria'].map(c=><option key={c}>{c}</option>)}</select><textarea placeholder="Testo" value={n.text} onChange={e=>setN({...n,text:e.target.value})}/><button onClick={()=>{actions.addNote(n);setN({...n,title:'',text:''})}}>Aggiungi nota</button></div></Card>{state.notes.slice().sort((a,b)=>Number(b.pinned)-Number(a.pinned)).map(note=><Card key={note.id}><h3>{note.pinned?'📌 ':''}{note.title}</h3><p>{note.text}</p><small>{note.category} · Fonte input: Note personali</small><div className="row"><button onClick={()=>actions.pinNote(note.id)}>Fissa</button><button className="ghost" onClick={()=>actions.deleteNote(note.id)}>Elimina</button></div></Card>)}</>; }
function Weather({state,actions}){ const [w,setW]=useState(state.weather); return <><SectionTitle title="Meteo" subtitle="Widget con icona e suggerimenti giornata."/><Card><div className="weatherHero"><Icon name={state.weather.icon}/><h2>{state.weather.temperature}°C</h2><p>{state.weather.condition} · {state.weather.city}</p></div><small>Fonte input: Servizio meteo / posizione utente. Ora dati mock pronti per API meteo.</small></Card><Card><div className="formGrid"><input value={w.city} onChange={e=>setW({...w,city:e.target.value})}/><input type="number" value={w.temperature??''} onChange={e=>setW({...w,temperature:e.target.value})}/><select value={w.condition} onChange={e=>setW({...w,condition:e.target.value})}>{['Sole','Nuvole','Pioggia','Temporale','Neve','Vento'].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Min" value={w.min??''} onChange={e=>setW({...w,min:e.target.value})}/><input placeholder="Max" value={w.max??''} onChange={e=>setW({...w,max:e.target.value})}/><input placeholder="Vento" value={w.wind??''} onChange={e=>setW({...w,wind:e.target.value})}/><button onClick={()=>actions.updateWeather(w)}>Aggiorna meteo</button></div></Card></>; }
function Notifications({state,actions}){ const [n,setN]=useState({title:'',message:'',category:'Generale',date:state.currentDate,time:'09:00'}); return <><SectionTitle title="Notifiche e promemoria"/><Card><div className="formGrid"><input placeholder="Titolo" value={n.title} onChange={e=>setN({...n,title:e.target.value})}/><input placeholder="Messaggio" value={n.message} onChange={e=>setN({...n,message:e.target.value})}/><input type="date" value={n.date} onChange={e=>setN({...n,date:e.target.value})}/><input type="time" value={n.time} onChange={e=>setN({...n,time:e.target.value})}/><select value={n.category} onChange={e=>setN({...n,category:e.target.value})}>{['Finanza','Salute','Fitness','Spesa','Note','Generale'].map(c=><option key={c}>{c}</option>)}</select><button onClick={()=>{actions.addNotification(n);setN({...n,title:'',message:''})}}>Aggiungi</button></div></Card>{state.notifications.map(x=><Card key={x.id}><h3>{x.title}</h3><p>{x.message}</p><small>{x.category} · {x.date} {x.time} · Stato: {x.status} · Fonte input: scadenze, farmaci, finanza, allenamenti</small><button onClick={()=>actions.completeNotification(x.id)}>Completa</button></Card>)}</>; }
function Suggestions({state}){ return <><SectionTitle title="Suggerimenti intelligenti" subtitle="Analisi automatica di pasti, spesa, finanza, allenamenti, salute e meteo."/>{state.suggestions.map((s,i)=><Card key={i}><h3>{s.action}</h3><p>{s.message}</p><small>Fonte input: Intelligence layer dell’ecosistema</small></Card>)}</>; }
function SettingsPage({state,actions}){ return <><SectionTitle title="Impostazioni" subtitle="Gestione locale, privacy, Apple Health e reset dati."/><Card><h3>Privacy</h3><p>I dati sono salvati nel browser tramite localStorage. Apple Health richiede consenso esplicito e qui è predisposto in mock.</p><small>Fonte input: configurazione app e preferenze utente</small></Card><Card><h3>Apple Health</h3><p>Stato: {state.appleHealth.connected?'collegato':'non collegato'}</p><button onClick={state.appleHealth.connected?actions.disconnectHealth:actions.connectHealth}>{state.appleHealth.connected?'Scollega':'Collega mock'}</button></Card><Card><h3>Reset</h3><button className="danger" onClick={actions.reset}>Cancella dati locali e riparti</button></Card></>; }

bootstrap();
createRoot(document.getElementById('root')).render(<App />);
